# Shell -->
shell /usr/bin/zsh

# Brackground section -->
background_opacity 0.40
background_blur 1

# Shortcuts setion -->
clear && printf '\e[3J'

# Fonts section -->
font_family JetBrainsMono Nerd Font Mono
bold_font JetBrainsMono Nerd Font Mono
italic_font JetBrainsMono Nerd Font Mono
bold_italic_font JetBrainsMono Nerd Font Mono

font_size 12

# Clipboard section -->
map ctrl+c copy_to_clipboard
map ctrl+v paste_from_clipboard

# Kill task -->
map ctrl+q close_window

# Kitty borders -->
hide_window_decorations yes
window_border_width 1.0pt
